using Assets.Scripts.Views;
using SimpleJSON;

namespace Assets.Scripts
{
    public static class LocalDatabase
    {
        public static JSONClass Data = new JSONClass
        {
            {
                "companies", new JSONClass
                {
                    { "Allianz",
                        new JSONClass { { "site", "http://www.allianz.ru/" }, { "icon", "Allianz" }, { "phone", new JSONClass { { "Москва", "+7 (495) 232-33-33" } } } } },
                    { "АМКОполис",
                        new JSONClass { { "site", "http://www.sk-amko.ru/" }, { "icon", "АМКОполис" }, { "phone", new JSONClass { { "Москва", "+7 (495) 545-39-11" } } } } },
                    { "Алроса",
                        new JSONClass { { "site", "http://www.ic-alrosa.ru/" }, { "icon", "Алроса" }, { "phone", new JSONClass { { "Москва", "+7 (495) 967-78-62" } } } } },
                    { "Альфа-Страхование",
                        new JSONClass { { "site", "http://www.alfastrah.ru/" }, { "icon", "Альфа-Страхование" }, { "phone", new JSONClass { { "Москва", "+7 (495) 788-09-99" } } } } },
                    { "Британский Страховой Дом",
                        new JSONClass { { "site", "http://bihouse.ru/" }, { "icon", "Британский Страховой Дом" }, { "phone", new JSONClass { { "Москва", "+7 (495) 755-53-35" } } } } },
                    { "ВСК Страховой Дом",
                        new JSONClass { { "site", "http://www.vsk.ru/" }, { "icon", "ВСК Страховой Дом" }, { "phone", new JSONClass { { "Москва", "+7 (495) 784-77-00" } } } } },
                    { "ВТБ",
                        new JSONClass { { "site", "http://www.vtbins.ru/" }, { "icon", "ВТБ" }, { "phone", new JSONClass { { "Москва", "+7 (495) 644-44-40" } } } } },
                    { "Гайде",
                        new JSONClass { { "site", "http://www.guideh.com/" }, { "icon", "Гайде" }, { "phone", new JSONClass { { "Москва", "8-800-444-02-75" } } } } },
                    { "Геополис",
                        new JSONClass { { "site", "http://www.geopolis.ru/" }, { "icon", "Геополис" }, { "phone", new JSONClass { { "Москва", "+7 (495) 22З-ЗЗ-6З" } } } } },
                    { "Гефест",
                        new JSONClass { { "site", "http://www.gefest.ru/" }, { "icon", "Гефест" }, { "phone", new JSONClass { { "Москва", "7 (495) 777-11-87" } } } } },
                    { "ЖАСО",
                        new JSONClass { { "site", "http://www.zhaso.ru/" }, { "icon", "ЖАСО" }, { "phone", new JSONClass { { "Москва", "+7 (495) 663-03-30" } } } } },
                    { "Инвест-Альянс",
                        new JSONClass { { "site", "http://ins-invest.ru/" }, { "icon", "Инвест-Альянс" }, { "phone", new JSONClass { { "Москва", "+7 (495) 783-23-20" } } } } },
                    { "Ингосстрах",
                        new JSONClass { { "site", "http://www.ingos.ru/ru/" }, { "icon", "Ингосстрах" }, { "phone", new JSONClass { { "Москва", "+7 (495) 956-55-55" }  } } } },
                    { "Компаньон",
                        new JSONClass { { "site", "http://companion-group.ru/" }, { "icon", "Компаньон" }, { "phone", new JSONClass { { "Москва", "+7 (495) 797-94-28" } } } } },
                    { "Купеческое",
                        new JSONClass { { "site", "http://www.kupecheskoe.ru/" }, { "icon", "Купеческое" }, { "phone", new JSONClass { { "Москва", "+7 (495) 685-94-67" } } } } },
                    { "Либерти Страхование (бывший КИТ Финанс)",
                        new JSONClass { { "site", "http://www.liberty24.ru/" }, { "icon", "Либерти Страхование (бывший КИТ Финанс)" }, { "phone", new JSONClass { { "Москва", "8-800-100-2-100" } } } } },
                    { "МАКС",
                        new JSONClass { { "site", "http://www.makc.ru/" }, { "icon", "МАКС" }, { "phone", new JSONClass { { "Москва", "+7 (495) 730-11-01" } } } } },
                    { "НАСКО",
                        new JSONClass { { "site", "http://nasko.ru/" }, { "icon", "НАСКО" }, { "phone", new JSONClass { { "Москва", "8-800-500-16-16" } } } } },
                    { "Объединённая Страховая Компания",
                        new JSONClass { { "site", "http://www.osk-ins.ru/" }, { "icon", "Объединённая Страховая Компания" }, { "phone", new JSONClass { { "Москва", "+7 (495) 981-29-77" } } } } },
                    { "Оранта Страхование",
                        new JSONClass { { "site", "http://www.oranta-sk.ru/" }, { "icon", "Оранта Страхование" }, { "phone", new JSONClass { { "Москва", "8-800-200-85-65" } } } } },
                    { "РЕСО-Гарантия",
                        new JSONClass { { "site", "http://www.reso.ru/" }, { "icon", "РЕСО-Гарантия" }, { "phone", new JSONClass { { "Москва", "+7 (495) 730-30-00" } } } } },
                    { "Ренессанс Страхование",
                        new JSONClass { { "site", "http://www.renins.com/" }, { "icon", "Ренессанс Страхование" }, { "phone", new JSONClass { { "Москва", "8-800-333-8-800" } } } } },
                    { "Росгосстрах",
                        new JSONClass { { "site", "http://www.rgs.ru/" }, { "icon", "Росгосстрах" }, { "phone", new JSONClass { { "Москва", "8-800-200-0-900" } } } } },
                    { "СГ Московская Страховая Компания",
                        new JSONClass { { "site", "http://sgmsk.ru/" }, { "icon", "СГ Московская Страховая Компания" }, { "phone", new JSONClass { { "Москва", "+7 (495) 956 84 84" } } } } },
                    { "СОГАЗ",
                        new JSONClass { { "site", "http://www.sogaz.ru/" }, { "icon", "СОГАЗ" }, { "phone", new JSONClass { { "Москва", "8-800-333-08-88" } } } } },
                    { "Северная Казна",
                        new JSONClass { { "site", "http://www.kazna.com/" }, { "icon", "Северная Казна" }, { "phone", new JSONClass { { "Москва", "8-800-700-13-30" } } } } },
                    { "Согласие",
                        new JSONClass { { "site", "http://www.soglasie.ru/" }, { "icon", "Согласие" }, { "phone", new JSONClass { { "Москва", "8-800-200-01-01" } } } } },
                    { "Сургутнефтегаз",
                        new JSONClass { { "site", "https://www.sngi.ru/" }, { "icon", "Сургутнефтегаз" }, { "phone", new JSONClass { { "Москва", "8-800-444-40-01" } } } } },
                    { "УралСиб",
                        new JSONClass { { "site", "http://www.uralsibins.ru/" }, { "icon", "УралСиб" }, { "phone", new JSONClass { { "Москва", "8-800-250-92-02" } } } } },
                    { "Цюрих",
                        new JSONClass { { "site", "http://www.zurich.ru/" }, { "icon", "Цюрих" }, { "phone", new JSONClass { { "Москва", "8-800-700-77-07 " } } } } },
                    { "Энергогарант",
                        new JSONClass { { "site", "http://www.energogarant.ru/" }, { "icon", "Энергогарант" }, { "phone", new JSONClass { { "Москва", "+7 (495) 737-03-30" } } } } },
                    { "Эрго Русь",
                        new JSONClass { { "site", "http://www.ergorussia.ru/" }, { "icon", "Эрго Русь" }, { "phone", new JSONClass { { "Москва", "8-800-200 22 24" } } } } },
                    { "Важно.Новое страхование",
                        new JSONClass { { "site", "https://www.vazhno.me/" }, { "icon", "Важно.Новое страхование" }, { "phone", new JSONClass { { "Москва", "8-800-333-88-63" } } } } },
                    { "Инвестиции и Финансы",
                        new JSONClass { { "site", "http://sk-if.ru/" }, { "icon", "Инвестиции и Финансы" }, { "phone", new JSONClass { { "Москва", "8-800-700-68-77" } } } } }
                }
            },
            {
                "regions", new JSONArray
                {
                    Regions.Default,
                    "Московская область",
                    "Санкт-Петербург",
                    "Астрахань",
                    "Барнаул",
                    "Белгород",
                    "Брянск",
                    "Владивосток",
                    "Волгоград",
                    "Воронеж",
                    "Екатеринбург",
                    "Иваново",
                    "Ижевск",
                    "Иркутск",
                    "Казань",
                    "Калининград",
                    "Кемерово",
                    "Киров",
                    "Краснодар",
                    "Красноярск",
                    "Курск",
                    "Липецк",
                    "Магнитогорск",
                    "Махачкала",
                    "Набережные Челны",
                    "Нижний Новгород",
                    "Нижний Тагил",
                    "Новокузнецк",
                    "Новосибирск",
                    "Омск",
                    "Оренбург",
                    "Пенза",
                    "Пермь",
                    "Ростов-на-Дону",
                    "Рязань",
                    "Самара",
                    "Саратов",
                    "Сочи",
                    "Ставрополь",
                    "Тверь",
                    "Тольятти",
                    "Томск",
                    "Тула",
                    "Тюмень",
                    "Улан-Удэ",
                    "Ульяновск",
                    "Уфа",
                    "Хабаровск",
                    "Чебоксары",
                    "Челябинск",
                    "Ярославль",
                    Regions.RequestRegion
                }
            },
            {
                "franchise", new JSONArray
                {
                    "0",
                    "5000",
                    "10000",
                    "15000",
                    "20000",
                    "25000",
                    "30000",
                }
            }
        };
    }
}