using Assets.Scripts.Views;
using SimpleJSON;

namespace Assets.Scripts
{
    public static class LocalDatabase
    {
        public static JSONClass Data = new JSONClass
        {
            {
                "companies", new JSONClass
                {
                    { "Allianz",
                        new JSONClass { { "site", "http://www.allianz.ru/" }, { "icon", "Allianz" }, { "phone", new JSONClass { { "Москва", "+7 495 232-33-33" } } }, { "reliability", "A++" } } },
                    { "АМКОполис",
                        new JSONClass { { "site", "http://www.sk-amko.ru/" }, { "icon", "АМКОполис" }, { "phone", new JSONClass { { "Москва", "+7 495 545-39-11" } } }, { "reliability", "нет данных" } } },
                    { "Алроса",
                        new JSONClass { { "site", "http://www.ic-alrosa.ru/" }, { "icon", "Алроса" }, { "phone", new JSONClass { { "Москва", "+7 495 967-78-62" } } }, { "reliability", "нет данных" } } },
                    { "Альфа-Страхование",
                        new JSONClass { { "site", "http://www.alfastrah.ru/" }, { "icon", "Альфа-Страхование" }, { "phone", new JSONClass { { "Москва", "+7 495 788-09-99" } } }, { "reliability", "A++" } } },
                    { "Британский Страховой Дом",
                        new JSONClass { { "site", "http://bihouse.ru/" }, { "icon", "Британский Страховой Дом" }, { "phone", new JSONClass { { "Москва", "+7 495 755-53-35" } } }, { "reliability", "А" } } },
                    { "ВСК Страховой Дом",
                        new JSONClass { { "site", "http://www.vsk.ru/" }, { "icon", "ВСК Страховой Дом" }, { "phone", new JSONClass { { "Москва", "+7 495 784-77-00" } } }, { "reliability", "A++" } } },
                    { "ВТБ",
                        new JSONClass { { "site", "http://www.vtbins.ru/" }, { "icon", "ВТБ" }, { "phone", new JSONClass { { "Москва", "+7 495 644-44-40" } } }, { "reliability", "A++" } } },
                    { "Гайде",
                        new JSONClass { { "site", "http://www.guideh.com/" }, { "icon", "Гайде" }, { "phone", new JSONClass { { "Москва", "8-800-444-02-75" } } }, { "reliability", "нет данных" } } },
                    { "Геополис",
                        new JSONClass { { "site", "http://www.geopolis.ru/" }, { "icon", "Геополис" }, { "phone", new JSONClass { { "Москва", "+7 495 22З-ЗЗ-6З" } } }, { "reliability", "A" } } },
                    { "Гефест",
                        new JSONClass { { "site", "http://www.gefest.ru/" }, { "icon", "Гефест" }, { "phone", new JSONClass { { "Москва", "+7 495 777-11-87" } } }, { "reliability", "A+" } } },
                    { "ЖАСО",
                        new JSONClass { { "site", "http://www.zhaso.ru/" }, { "icon", "ЖАСО" }, { "phone", new JSONClass { { "Москва", "+7 495 663-03-30" } } }, { "reliability", "A++" } } },
                    { "Инвест-Альянс",
                        new JSONClass { { "site", "http://ins-invest.ru/" }, { "icon", "Инвест-Альянс" }, { "phone", new JSONClass { { "Москва", "+7 495 783-23-20" } } }, { "reliability", "нет данных" } } },
                    { "Ингосстрах",
                        new JSONClass { { "site", "http://www.ingos.ru/ru/" }, { "icon", "Ингосстрах" }, { "phone", new JSONClass { { "Москва", "+7 495 956-55-55" } } }, { "reliability", "A++" } } },
                    { "Компаньон",
                        new JSONClass { { "site", "http://companion-group.ru/" }, { "icon", "Компаньон" }, { "phone", new JSONClass { { "Москва", "+7 495 797-94-28" } } }, { "reliability", "нет данных" } } },
                    { "Купеческое",
                        new JSONClass { { "site", "http://www.kupecheskoe.ru/" }, { "icon", "Купеческое" }, { "phone", new JSONClass { { "Москва", "+7 495 685-94-67" } } }, { "reliability", "нет данных" } } },
                    { "Либерти Страхование (бывший КИТ Финанс)",
                        new JSONClass { { "site", "http://www.liberty24.ru/" }, { "icon", "Либерти Страхование (бывший КИТ Финанс)" }, { "phone", new JSONClass { { "Москва", "8-800-100-2-100" } } }, { "reliability", "A+" } } },
                    { "МАКС",
                        new JSONClass { { "site", "http://www.makc.ru/" }, { "icon", "МАКС" }, { "phone", new JSONClass { { "Москва", "+7 495 730-11-01" } } }, { "reliability", "A++" } } },
                    { "НАСКО",
                        new JSONClass { { "site", "http://nasko.ru/" }, { "icon", "НАСКО" }, { "phone", new JSONClass { { "Москва", "8-800-500-16-16" } } }, { "reliability", "A+" } } },
                    { "Объединённая Страховая Компания",
                        new JSONClass { { "site", "http://www.osk-ins.ru/" }, { "icon", "Объединённая Страховая Компания" }, { "phone", new JSONClass { { "Москва", "+7 495 981-29-77" } } }, { "reliability", "A+" } } },
                    { "Оранта Страхование",
                        new JSONClass { { "site", "http://www.oranta-sk.ru/" }, { "icon", "Оранта Страхование" }, { "phone", new JSONClass { { "Москва", "8-800-200-85-65" } } }, { "reliability", "А+" } } },
                    { "РЕСО-Гарантия",
                        new JSONClass { { "site", "http://www.reso.ru/" }, { "icon", "РЕСО-Гарантия" }, { "phone", new JSONClass { { "Москва", "+7 495 730-30-00" } } }, { "reliability", "нет данных" } } },
                    { "Ренессанс Страхование",
                        new JSONClass { { "site", "http://www.renins.com/" }, { "icon", "Ренессанс Страхование" }, { "phone", new JSONClass { { "Москва", "8-800-333-8-800" } } }, { "reliability", "A++" } } },
                    { "Росгосстрах",
                        new JSONClass { { "site", "http://www.rgs.ru/" }, { "icon", "Росгосстрах" }, { "phone", new JSONClass { { "Москва", "8-800-200-0-900" } } }, { "reliability", "A++" } } },
                    { "СГ Московская Страховая Компания",
                        new JSONClass { { "site", "http://sgmsk.ru/" }, { "icon", "СГ Московская Страховая Компания" }, { "phone", new JSONClass { { "Москва", "+7 495 956 84 84" } } }, { "reliability", "А+" } } },
                    { "СОГАЗ",
                        new JSONClass { { "site", "http://www.sogaz.ru/" }, { "icon", "СОГАЗ" }, { "phone", new JSONClass { { "Москва", "8-800-333-08-88" } } }, { "reliability", "A++" } } },
                    { "Северная Казна",
                        new JSONClass { { "site", "http://www.kazna.com/" }, { "icon", "Северная Казна" }, { "phone", new JSONClass { { "Москва", "8-800-700-13-30" } } }, { "reliability", "А" } } },
                    { "Согласие",
                        new JSONClass { { "site", "http://www.soglasie.ru/" }, { "icon", "Согласие" }, { "phone", new JSONClass { { "Москва", "8-800-200-01-01" } } }, { "reliability", "A++" } } },
                    { "Сургутнефтегаз",
                        new JSONClass { { "site", "https://www.sngi.ru/" }, { "icon", "Сургутнефтегаз" }, { "phone", new JSONClass { { "Москва", "8-800-444-40-01" } } }, { "reliability", "A+" } } },
                    { "УралСиб",
                        new JSONClass { { "site", "http://www.uralsibins.ru/" }, { "icon", "УралСиб" }, { "phone", new JSONClass { { "Москва", "8-800-250-92-02" } } }, { "reliability", "A++" } } },
                    { "Цюрих",
                        new JSONClass { { "site", "http://www.zurich.ru/" }, { "icon", "Цюрих" }, { "phone", new JSONClass { { "Москва", "8-800-700-77-07 " } } }, { "reliability", "A+" } } },
                    { "Энергогарант",
                        new JSONClass { { "site", "http://www.energogarant.ru/" }, { "icon", "Энергогарант" }, { "phone", new JSONClass { { "Москва", "+7 495 737-03-30" } } }, { "reliability", "A++" } } },
                    { "Эрго Русь",
                        new JSONClass { { "site", "http://www.ergorussia.ru/" }, { "icon", "Эрго Русь" }, { "phone", new JSONClass { { "Москва", "8-800-200 22 24" } } }, { "reliability", "A+" } } },
                    { "Важно.Новое страхование",
                        new JSONClass { { "site", "https://www.vazhno.me/" }, { "icon", "Важно.Новое страхование" }, { "phone", new JSONClass { { "Москва", "8-800-333-88-63" } } }, { "reliability", "нет данных" } } },
                    { "Инвестиции и Финансы",
                        new JSONClass { { "site", "http://sk-if.ru/" }, { "icon", "Инвестиции и Финансы" }, { "phone", new JSONClass { { "Москва", "8-800-700-68-77" } } }, { "reliability", "А" } } }
                }
            },
            {
                "regions", new JSONArray
                {
                    Region.Default,
                    "Санкт-Петербург",
                    "Абакан",
                    "Анадырь",
                    "Архангельск",
                    "Астрахань",
                    "Барнаул",
                    "Белгород",
                    "Биробиджан",
                    "Благовещенск",
                    "Брянск",
                    "Великий Новгород",
                    "Владивосток",
                    "Владимир",
                    "Волгоград",
                    "Вологда",
                    "Воронеж",
                    "Горно-Алтайск",
                    "Екатеринбург",
                    "Иваново",
                    "Ижевск",
                    "Иркутск",
                    "Йошкар-Ола",
                    "Казань",
                    "Калининград",
                    "Калуга",
                    "Кемерово",
                    "Киров",
                    "Кострома",
                    "Краснодар",
                    "Красноярск",
                    "Курган",
                    "Курск",
                    "Кызыл",
                    "Липецк",
                    "Магадан",
                    "Магнитогорск",
                    "Майкоп",
                    "Мурманск",
                    "Набережные Челны",
                    "Нижний Новгород",
                    "Новороссийск",
                    "Новосибирск",
                    "Омск",
                    "Орел",
                    "Оренбург",
                    "Пенза",
                    "Пермь",
                    "Петрозаводск",
                    "Петропавловск-Камчатский",
                    "Псков",
                    "Ростов-на-Дону",
                    "Рязань",
                    "Самара",
                    "Саранск",
                    "Саратов",
                    "Смоленск",
                    "Ставрополь",
                    "Сургут",
                    "Сыктывкар",
                    "Тамбов",
                    "Тверь",
                    "Тольятти",
                    "Томск",
                    "Тула",
                    "Тюмень",
                    "Улан-Удэ",
                    "Ульяновск",
                    "Уфа",
                    "Хабаровск",
                    "Ханты-Мансийск",
                    "Чебоксары",
                    "Челябинск",
                    "Чита",
                    "Элиста",
                    "Южно-Сахалинск",
                    "Якутск",
                    "Ярославль",
                    Region.RequestRegion
                }
            },
            {
                "franchise", new JSONArray
                {
                    "0",
                    "5000",
                    "10000",
                    "15000",
                    "20000",
                    "25000",
                    "30000",
                }
            },
            {
                "kbm", new JSONClass
                {
                    "класс М (2.45)",
                    "класс 0 (2.3)",
                    "класс 1 (1.55)",
                    "класс 2 (1.4)",
                    "класс 3 (1)",
                    "класс 4 (0.95)",
                    "класс 5 (0.9)",
                    "класс 6 (0.85)",
                    "класс 7 (0.8)",
                    "класс 8 (0.75)",
                    "класс 9 (0.7)",
                    "класс 10 (0.65)",
                    "класс 11 (0.6)",
                    "класс 12 (0.55)",
                    "класс 13 (0.5)"
                }
            }
        };
    }
}